// THE QUESTS — the heart of Void. You can edit these without knowing how to code.
//
// Every quest is a JOB SAMPLE: a small, real version of the work people do in a career.
// You do it, then log how it felt. The pattern across quests points at careers worth researching.
//
//   cat:   make | move | learn | social | nature | give   (the six fields you sweep in Phase 1)
//   tier:  recon (under an hour, solo, no permission needed)
//          mission (1-3 hours, may involve one person)
//          trial (bigger or more uncomfortable: real exposure to a real workplace or person)
//   tests: careers this quest samples (shown on the card, and used by the Direction Report)
//   why:   what this quest is designed to reveal about you
const QUESTS = [
  // ================= CREATE: design, build, make =================
  { id: 1, cat: "make", tier: "recon", time: "45 min", title: "Design a poster for something real",
    desc: "Pick a real local event, a friend's band, or a product you'd actually like to exist. Make a poster in a free tool like Canva, Figma or Photopea. Export it and look at it with fresh eyes.",
    why: "Graphic design is solving a message problem visually. See whether 45 minutes flew by or dragged.",
    tests: "graphic design, branding, marketing, advertising" },
  { id: 2, cat: "make", tier: "recon", time: "45 min", title: "Build a one-page website",
    desc: "Follow a free beginner tutorial (freeCodeCamp, MDN, YouTube) and build a page about something you care about. Get it showing in your browser. Notice how you handle getting stuck.",
    why: "Developers spend most of their time stuck and unstuck. Find out whether that loop pulls you in or wears you out.",
    tests: "web development, software engineering, UX design, game development" },
  { id: 3, cat: "make", tier: "recon", time: "45 min", title: "Cut a 60-second video",
    desc: "Film five clips on your phone and edit them into a 60-second video with a free editor (CapCut, DaVinci Resolve). Add music and one title. Export it.",
    why: "Editing is choosing what to leave out, hundreds of times. See whether that precision is satisfying or tedious.",
    tests: "video editing, filmmaking, content creation, advertising, social media" },
  { id: 4, cat: "make", tier: "recon", time: "45 min", title: "Redesign a room on paper",
    desc: "Measure a room you know. Draw it to scale on paper or in a free planner like Floorplanner. Rearrange it for how it's actually used, and write down three problems your new layout solves.",
    why: "Spatial design is about fitting real needs into real limits. It's a very different feeling from open-ended creativity.",
    tests: "architecture, interior design, civil engineering, construction management" },
  { id: 5, cat: "make", tier: "mission", time: "2 hours", title: "Fix something that's broken",
    desc: "A tap, a bike, a laptop key, an appliance, a hole in a wall. Find a repair guide, get the right tools, and fix it yourself. Note which moments you liked: diagnosing, working, or finishing.",
    why: "Repair work is diagnosis plus hands-on work. Some people love the puzzle, some love the doing, some hate both.",
    tests: "electrician, plumber, mechanic, maintenance technician, mechanical engineering" },
  { id: 6, cat: "make", tier: "mission", time: "2-3 hours", title: "Cook a proper meal for four on a budget",
    desc: "Plan a menu, cost it, shop for it, prep it and serve it to at least three other people, with everything ready at the same time.",
    why: "Cooking for others is planning, speed and pressure at once. See whether the timing stress energises you or drains you.",
    tests: "chef, catering, hospitality, food business, food science" },
  { id: 7, cat: "make", tier: "trial", time: "3-4 hours", title: "Make something for a real person and deliver it",
    desc: "Find someone who needs something: a friend's band needs a logo, a local shop needs a flyer, a relative needs a simple website. Ask what they need, make it, deliver it, and ask what they'd change.",
    why: "This is freelancing in miniature: understanding a need, making it, and hearing the feedback. Notice which part you avoided.",
    tests: "freelance design, web development, marketing, small business ownership" },

  // ================= BODY: physical, hands-on, active =================
  { id: 8, cat: "move", tier: "recon", time: "40 min", title: "Assess your fitness and write a plan",
    desc: "Test yourself with a few basics (max push-ups, a timed run, a plank, how far you can reach). Then write a four-week plan to improve one weakness, explaining why each exercise is in it.",
    why: "Coaching is assessing a body and designing a plan. See whether you enjoy that analysis, not just the exercise.",
    tests: "personal trainer, physiotherapy, sports science, strength coach" },
  { id: 9, cat: "move", tier: "recon", time: "40 min", title: "Learn basic first aid",
    desc: "Work through a free first aid course or guide (CPR, bleeding, choking, recovery position). Practise CPR timing on a cushion. Pay attention to how you feel about the idea of using it for real.",
    why: "Emergency and health work asks you to act calmly with someone's wellbeing at stake. This is a safe first look at that.",
    tests: "paramedic, nurse, emergency services, lifeguard, occupational health" },
  { id: 10, cat: "move", tier: "mission", time: "90 min", title: "Take a session led by a professional coach",
    desc: "Book a trial class (boxing, BJJ, climbing, CrossFit, swim squad, running club). Do the session, but also watch how the coach runs it: how they teach, correct and motivate.",
    why: "Seeing the coach's job from the inside shows whether you'd want to be the person leading the room.",
    tests: "coaching, sports instruction, fitness business, PE teaching, sports science" },
  { id: 11, cat: "move", tier: "mission", time: "90 min", title: "Test yourself against a real physical job",
    desc: "Pick a physical job (firefighter, paramedic, builder, farm worker, forestry). Watch a day-in-the-life video, find its fitness or skills test, and try a safe version of the hardest part.",
    why: "Many physical jobs reward people who like pushing against real resistance all day. Notice whether you'd want that for years.",
    tests: "firefighter, emergency services, military, construction, farming, forestry" },
  { id: 12, cat: "move", tier: "mission", time: "1 hour", title: "Ask a physio, trainer or paramedic about their week",
    desc: "Find someone working in a body-focused career. Ask what a normal week looks like, what the training took, what the hardest part is, and what they'd tell a 20-year-old.",
    why: "Health and fitness jobs look very different up close than on social media. Hear the real version.",
    tests: "physiotherapy, personal training, paramedic, sports therapy, nursing" },
  { id: 13, cat: "move", tier: "trial", time: "Half a day", title: "Book a real taster for a physical career",
    desc: "Sign up for something that leads somewhere: a gym instructor course intro, a lifeguard qualification session, a fire service open day, an apprenticeship taster, a pre-service fitness session. Then go.",
    why: "Showing up to a taster is a real commitment. What you feel in the room tells you more than any article.",
    tests: "fitness instructor, lifeguard, emergency services, trades apprenticeship, military" },

  // ================= MIND: analysis, tech, research =================
  { id: 14, cat: "learn", tier: "recon", time: "40 min", title: "Find one real insight in a dataset",
    desc: "Download a free dataset you care about (sports stats, local weather, your own phone usage). Use a spreadsheet to find one real insight and make one chart. Write the insight in a single sentence.",
    why: "Analysis is the patient hunt for something true. See whether the hunt pulls you in.",
    tests: "data analysis, finance, sports analytics, business analytics, research" },
  { id: 15, cat: "learn", tier: "recon", time: "45 min", title: "Write your first program",
    desc: "Do a beginner coding lesson (freeCodeCamp, CS50 intro, Codecademy free) until something you wrote actually runs. Notice whether being stuck feels frustrating or oddly enjoyable.",
    why: "Software work is mostly getting unstuck. This is the fastest honest test of whether that loop suits you.",
    tests: "software engineering, data science, cybersecurity, game development" },
  { id: 16, cat: "learn", tier: "mission", time: "2 hours", title: "Sit through a real intro lecture and take notes",
    desc: "Pick a field (psychology, economics, medicine, law, engineering, philosophy). Watch a full university intro lecture with notes. Mark the moment you were most curious and what you wanted to look up.",
    why: "Curiosity is the earliest sign of a path. A sustained 90 minutes shows if it's real.",
    tests: "research, academia, medicine, law, engineering, psychology" },
  { id: 17, cat: "learn", tier: "mission", time: "90 min", title: "Read real job ads and salary data for three careers",
    desc: "Pick three careers that interest you. Read real job ads and an official salary source. Write down what each pays, what it requires, and what the work actually involves day to day.",
    why: "Most people choose jobs by their title. The requirements and daily tasks show what you'd really be doing.",
    tests: "career research, any career" },
  { id: 18, cat: "learn", tier: "mission", time: "2 hours", title: "Work out how a business really makes money",
    desc: "Pick a company you like. Find where its money comes from, its biggest costs, who its competitors are, and what could go wrong. Write one page.",
    why: "Business thinking is seeing the money underneath a product. See whether that view fascinates you.",
    tests: "business analysis, consulting, finance, management, entrepreneurship" },
  { id: 19, cat: "learn", tier: "trial", time: "3 hours", title: "Answer a real question with real evidence",
    desc: "Choose a question you care about (Which local gym is best value? Why do people drop out of courses?). Gather evidence from at least five sources or people and write a one-page answer.",
    why: "Research means committing to a question and following the evidence, even when it's tedious. See if you can stay with it.",
    tests: "research, journalism, consulting, policy analysis, data analysis" },

  // ================= PEOPLE: sales, teaching, leading, communicating =================
  { id: 20, cat: "social", tier: "recon", time: "20 min", title: "Message a professional with one specific question",
    desc: "Find someone doing work you're curious about and send a short, specific note: what you saw of their work, and one question. Don't ask for anything else.",
    why: "Reaching out is a core career skill. How you feel sending it shows how much you want to know the answer.",
    tests: "any career, networking" },
  { id: 21, cat: "social", tier: "recon", time: "20 min", title: "Ask three people what you're naturally good at",
    desc: "Text three people who know you well: \"What do you think I'm naturally good at?\" Ask for specific examples. Look for the pattern across all three.",
    why: "Other people see strengths in you that you take for granted.",
    tests: "any career, self-knowledge" },
  { id: 22, cat: "social", tier: "mission", time: "45 min", title: "Do an informational interview",
    desc: "Find someone in a job you're curious about. Ask: What does a normal Tuesday look like? What's the worst part? What surprised you? What would you do differently?",
    why: "The daily reality of a job is what you'd actually be signing up for, not the title.",
    tests: "any career" },
  { id: 23, cat: "social", tier: "mission", time: "1-2 hours", title: "Sell something small to a real person",
    desc: "Sell one real thing: something you own, or a simple service like car washing or tutoring. Make the offer, ask for the sale, and handle at least one 'no'.",
    why: "Sales is asking, hearing no, and trying again. This is the quickest real test of whether you can stand that.",
    tests: "sales, business development, entrepreneurship, retail management" },
  { id: 24, cat: "social", tier: "mission", time: "1 hour", title: "Lead a 30-minute group session",
    desc: "Organise and lead something for at least three people: a study group, a planning session, a game night, a workout. Set the goal, run it, and keep it moving.",
    why: "Leading a group is a different skill from joining one. See whether you enjoy steering it.",
    tests: "management, event planning, teaching, HR, team leading" },
  { id: 25, cat: "social", tier: "trial", time: "A day", title: "Ask to shadow someone for a day",
    desc: "Contact a local professional and ask if you can follow them for a day. Be polite, clear and ready to hear no. If they say yes, take notes on what they actually do.",
    why: "Asking is the first test. A day inside a real job is the second, and it tells you more than any article.",
    tests: "any career, workplace exposure" },

  // ================= EXPLORE: field work, outdoors, operations =================
  { id: 26, cat: "nature", tier: "recon", time: "45 min", title: "Watch three field jobs and rank them",
    desc: "Watch a day-in-the-life video for three outdoor or field jobs (surveyor, park ranger, farmer, pilot, forestry, environmental technician). Rank them by which you'd try for a week and write why.",
    why: "Your ranking is data. Notice what drew you: the place, the tools, or the freedom.",
    tests: "surveying, conservation, farming, aviation, forestry, environmental work" },
  { id: 27, cat: "nature", tier: "recon", time: "40 min", title: "Plan a trip as a logistics problem",
    desc: "Plan a one-day trip for four people: routes, timings, costs and a backup plan if something fails. Make the plan so clear that someone else could follow it.",
    why: "Logistics is solving moving parts under constraints. See whether that feels like a puzzle or a chore.",
    tests: "logistics, operations, travel and tourism, event management, supply chain" },
  { id: 28, cat: "nature", tier: "mission", time: "2 hours", title: "Visit a workplace and watch people work",
    desc: "A workshop open day, a farm, a market, a port, a depot, a fire station, a studio. Go and watch people do their jobs. Note the pace, the noise, the people and the tools.",
    why: "You can only picture yourself in a job after you've seen it up close.",
    tests: "any career, workplace exposure" },
  { id: 29, cat: "nature", tier: "mission", time: "2-3 hours", title: "Plan and complete a solo mini-expedition",
    desc: "Plan a 2-3 hour walk or ride to a place you've never been, using a map. Decide the route, timing and what you'll carry. Tell someone where you're going.",
    why: "Being the person responsible for the plan shows whether you like leading yourself.",
    tests: "outdoor guiding, surveying, search and rescue, military, expedition leading" },
  { id: 30, cat: "nature", tier: "mission", time: "90 min", title: "Study how an environment job really works",
    desc: "Pick a career like conservation officer, marine biologist, urban planner, agronomist. Find the real training route, pay, and daily tasks. Write what's surprising.",
    why: "Environment careers vary hugely in how outdoors the work really is. Know before you commit.",
    tests: "conservation, marine biology, urban planning, agriculture, environmental science" },
  { id: 31, cat: "nature", tier: "trial", time: "A full day", title: "Volunteer for a day in an outdoor or field setting",
    desc: "Join a conservation work party, a community garden build, a farm volunteer day or a trail-maintenance crew. Work a full day alongside the people who do it.",
    why: "A full day of real, tiring field work shows you what the career would actually feel like.",
    tests: "conservation, agriculture, land management, outdoor education, groundskeeping" },

  // ================= SERVE: care, teaching, community =================
  { id: 32, cat: "give", tier: "recon", time: "30 min", title: "Listen to someone for 20 minutes without fixing anything",
    desc: "Ask someone how they're really doing, then listen. No advice, no solutions, no phone. Just ask follow-up questions. Afterwards note how it felt for you.",
    why: "Counselling and care work start here. Some people find it energising, some find it draining. Both are useful to know.",
    tests: "counselling, social work, nursing, coaching, HR" },
  { id: 33, cat: "give", tier: "recon", time: "40 min", title: "Find out how someone actually becomes a nurse, teacher or social worker",
    desc: "Pick one caring profession. Find the real training route, length, cost and starting pay in your area, and the biggest challenges people mention. Write your findings in a few lines.",
    why: "A path feels real once you can see its first step.",
    tests: "nursing, teaching, social work, youth work, paramedic" },
  { id: 34, cat: "give", tier: "mission", time: "1 hour", title: "Teach someone a real skill",
    desc: "Teach a friend or family member something you actually know, using a simple plan: goal, steps, and a check at the end. Notice the moments they 'get it' and how that feels.",
    why: "Teaching shows whether you get energy from other people's progress.",
    tests: "teaching, training, coaching, tutoring" },
  { id: 35, cat: "give", tier: "mission", time: "90 min", title: "Help someone with a real life problem",
    desc: "Help someone with a real task: filling in a form, writing a CV, setting up a budget, fixing a phone. Do it properly and notice whether being useful energises you.",
    why: "Solving someone's actual problem is the heart of service jobs. See whether it feels like fuel or a drain.",
    tests: "social work, advice and guidance, community services, customer support" },
  { id: 36, cat: "give", tier: "mission", time: "One shift", title: "Volunteer for one shift",
    desc: "Food bank, animal shelter, community clean-up, youth sports. Sign up and show up for a full shift. Talk to one person who works there year-round.",
    why: "Some people find their direction in serving. Spend a real shift and see whether you feel it.",
    tests: "non-profit work, community work, animal care, youth work, public service" },
  { id: 37, cat: "give", tier: "trial", time: "2 hours", title: "Coach or tutor someone for an hour",
    desc: "Offer to help a younger person (a cousin, a neighbour, a local club) with homework, a sport or a CV. Prepare a simple plan. Afterwards write what they got from it.",
    why: "Taking responsibility for someone else's progress shows what kind of leader you'd be.",
    tests: "teaching, youth work, coaching, mentoring, leadership" },

  // ================= PREMIUM PACK: THE BUILDER PATH =================
  { id: 101, pack: "builder", cat: "learn", tier: "recon", time: "30 min", title: "Find a problem worth solving",
    desc: "List ten things that annoyed you this week, big or small. Circle the three other people probably share.",
    why: "Every real business starts with a problem you're close enough to feel.",
    tests: "entrepreneurship, product management" },
  { id: 102, pack: "builder", cat: "learn", tier: "recon", time: "30 min", title: "Study a business near you",
    desc: "Pick a local business. Work out who pays them, for what, and how they probably got their first customers.",
    why: "Seeing how money actually moves makes building something feel less abstract.",
    tests: "entrepreneurship, business analysis, small business ownership" },
  { id: 103, pack: "builder", cat: "social", tier: "mission", time: "1 hour", title: "Ask three people about a problem",
    desc: "Pick a problem you care about. Ask three people whether they have it and what they do about it now. Don't pitch anything. Just listen.",
    why: "Listening before building is the skill most first-time founders skip.",
    tests: "entrepreneurship, product management, user research" },
  { id: 104, pack: "builder", cat: "make", tier: "mission", time: "2 hours", title: "Build the smallest possible test",
    desc: "A one-page site, a mock-up, a spreadsheet, a short pitch. Anything a stranger could react to in under a minute.",
    why: "Shows whether you enjoy turning an idea into something real, fast and rough.",
    tests: "entrepreneurship, product design, software engineering" },
  { id: 105, pack: "builder", cat: "make", tier: "mission", time: "1 hour", title: "Put a price on it",
    desc: "Decide what your idea would cost and write down why. Then ask two people whether it feels fair.",
    why: "Pricing forces you to believe your idea is worth something.",
    tests: "entrepreneurship, sales, business development" },
  { id: 106, pack: "builder", cat: "learn", tier: "mission", time: "90 min", title: "Read a founder's first year",
    desc: "Find a long, honest account of a founder's first year: an interview, a podcast, a blog. Note the unglamorous parts.",
    why: "If the boring parts sound bearable, that's a strong sign.",
    tests: "entrepreneurship, startups" },
  { id: 107, pack: "builder", cat: "social", tier: "trial", time: "3 hours", title: "Get a stranger to say yes or no",
    desc: "Show what you made to someone you don't know and ask them to buy it, sign up or commit. A no counts as a win.",
    why: "Handling rejection decides whether you can build anything for other people.",
    tests: "sales, entrepreneurship, business development" },
  { id: 108, pack: "builder", cat: "give", tier: "trial", time: "3 hours", title: "Solve it for one person for free",
    desc: "Offer to solve the problem for one person at no charge. Do it properly. Notice how it feels to be useful.",
    why: "Shows whether the work itself, not the money, is what pulls you.",
    tests: "entrepreneurship, consulting, freelancing" },

  // ================= PREMIUM PACK: HANDS & TRADES =================
  { id: 111, pack: "trades", cat: "social", tier: "recon", time: "20 min", title: "Ask a tradesperson what they'd tell a 20-year-old",
    desc: "An electrician, carpenter, mechanic, plumber, welder. Ask what the job is really like and how they got started.",
    why: "Trades are well paid and under-explored. Hear it from someone actually doing it.",
    tests: "electrician, carpenter, mechanic, plumber, welder" },
  { id: 112, pack: "trades", cat: "learn", tier: "recon", time: "30 min", title: "Look up three apprenticeships",
    desc: "Find the entry route, length, pay and requirements for three trades near you. Write them side by side.",
    why: "A real path is easier to want when you can see its first step.",
    tests: "apprenticeships, skilled trades" },
  { id: 113, pack: "trades", cat: "make", tier: "mission", time: "90 min", title: "Do a small repair with real tools",
    desc: "Replace a tap washer, patch a wall, change a bike chain, swap a plug. Follow a tutorial and do it for real.",
    why: "Hands-on work either feels satisfying or it doesn't. Find out which.",
    tests: "plumber, electrician, carpenter, maintenance technician" },
  { id: 114, pack: "trades", cat: "nature", tier: "mission", time: "1-2 hours", title: "Watch a trade at work",
    desc: "Ask a local tradesperson or workshop if you can watch for an hour. Notice the pace, the tools and the mood.",
    why: "You can only picture yourself in a job after you've seen it up close.",
    tests: "skilled trades, construction" },
  { id: 115, pack: "trades", cat: "move", tier: "mission", time: "3 hours", title: "Do a physical day's labour",
    desc: "Help someone move house, dig a garden, build a fence or clear a space. Three hours of real physical work.",
    why: "Shows whether you enjoy work that ends in something you can see.",
    tests: "construction, landscaping, trades labour" },
  { id: 116, pack: "trades", cat: "learn", tier: "mission", time: "90 min", title: "Learn to read a plan or diagram",
    desc: "Learn to read a basic floor plan, wiring diagram or technical drawing. Find a beginner guide and work through one example.",
    why: "Technical thinking is the core of most skilled trades.",
    tests: "electrician, construction, engineering technician" },
  { id: 117, pack: "trades", cat: "make", tier: "trial", time: "4 hours", title: "Build something that has to hold weight",
    desc: "A shelf, a bench, a frame. It has to work, and it has to survive being used.",
    why: "When it has to work, you find out how you handle precision and mistakes.",
    tests: "carpenter, joiner, construction" },
  { id: 118, pack: "trades", cat: "social", tier: "trial", time: "Half a day", title: "Ask for a day of work experience",
    desc: "Contact a local business and ask if you can shadow someone for a day. Be polite, clear and ready to be told no.",
    why: "Asking for the chance is itself a test of how much you want it.",
    tests: "skilled trades, workplace exposure" },

  // ================= PREMIUM PACK: CREATIVE PATHS =================
  { id: 121, pack: "creative", cat: "make", tier: "recon", time: "30 min", title: "Make ten rough versions",
    desc: "Take one idea (a logo, a hook, a scene, a sketch) and make ten rough versions in 30 minutes. Don't judge until all ten exist.",
    why: "Creative careers reward volume. See whether you enjoy the churn.",
    tests: "graphic design, illustration, songwriting, advertising" },
  { id: 122, pack: "creative", cat: "learn", tier: "recon", time: "30 min", title: "Break down something you love",
    desc: "Take a film scene, a song or a design you love and work out exactly why it works.",
    why: "What you notice shows what you're drawn to making.",
    tests: "film, music, design, writing" },
  { id: 123, pack: "creative", cat: "make", tier: "mission", time: "2 hours", title: "Finish a piece under constraints",
    desc: "Set tight rules: one colour, three chords, 100 words, one location. Finish something in two hours.",
    why: "Constraints show whether you get energy from limits or feel stifled by them.",
    tests: "art direction, advertising, filmmaking, music production" },
  { id: 124, pack: "creative", cat: "social", tier: "mission", time: "45 min", title: "Ask a working creative how they get paid",
    desc: "Message or meet someone who earns from creative work. Ask how they started, how they price their work and what the first year was like.",
    why: "The money side of creative work is where most dreams get tested.",
    tests: "freelance creative, design, music, film" },
  { id: 125, pack: "creative", cat: "make", tier: "mission", time: "15 min a day, 7 days", title: "Run a seven-day practice",
    desc: "Pick one creative practice and do 15 minutes a day for seven days. Log it, even when it's bad.",
    why: "Seven days is enough to show whether you want to keep going once it's no longer new.",
    tests: "any creative career" },
  { id: 126, pack: "creative", cat: "learn", tier: "mission", time: "90 min", title: "Study how a creative career really works",
    desc: "Pick a career: illustration, audio engineering, game design, filmmaking. Find out how people earn, what the entry jobs are and what a typical week looks like.",
    why: "Knowing the real shape of a career lets you decide whether you want it.",
    tests: "illustration, audio engineering, game design, filmmaking" },
  { id: 127, pack: "creative", cat: "social", tier: "trial", time: "2 hours", title: "Show unfinished work to a stranger",
    desc: "Share something half-done with someone you don't know and ask what they notice. Don't defend it.",
    why: "Tolerance for feedback is one of the biggest predictors of a creative career.",
    tests: "any creative career" },
  { id: 128, pack: "creative", cat: "make", tier: "trial", time: "4 hours", title: "Make something for a real deadline",
    desc: "Pick a real deadline: a friend's birthday, a local event, a submission date. Make something for it and ship it on time.",
    why: "Deadlines show whether you work better under pressure or in spite of it.",
    tests: "freelance creative, advertising, film, design" }
];

const TIERS = {
  recon:   { label: "Recon",   xp: 50,  gear: "common" },
  mission: { label: "Mission", xp: 100, gear: "rare" },
  trial:   { label: "Trial",   xp: 200, gear: "epic" }
};

// The six fields you sweep in Phase 1. "ask" is the reflection prompt shown after a quest in that field.
const CATEGORIES = {
  make:   { label: "Create",  color: "#c58a9f", ask: "Which part did you like most: starting, making, or finishing?" },
  move:   { label: "Body",    color: "#c9965c", ask: "How did you feel when it got hard?" },
  learn:  { label: "Mind",    color: "#6f97b8", ask: "What did you want to look up next?" },
  social: { label: "People",  color: "#c47f6c", ask: "What did you learn about what they actually do or feel?" },
  nature: { label: "Explore", color: "#6f9f86", ask: "What did you think about when it went quiet?" },
  give:   { label: "Serve",   color: "#c4ad72", ask: "What did it feel like to do it?" }
};

// Premium quest packs (sold in the Shop). Quests with a "pack" only appear once that pack is owned.
const PACKS = {
  builder:  { name: "The Builder Path", tag: "For people who want to start something of their own." },
  trades:   { name: "Hands & Trades",   tag: "Test skilled trades and practical, physical work." },
  creative: { name: "Creative Paths",   tag: "Find out if a creative career is really for you." }
};

// Used by the Direction Report as a fallback. Not career advice: just paths people with each signal often explore.
const FIELD_PATHS = {
  make:   "design, engineering, film and video, game development, architecture, the skilled trades",
  move:   "coaching, physiotherapy, sports science, emergency services, the military, outdoor education",
  learn:  "research, engineering, medicine, law, data and analysis, writing",
  social: "sales, teaching, counselling, recruiting, management, community work",
  nature: "surveying, logistics, conservation, travel and hospitality, field work, outdoor roles",
  give:   "nursing, social work, teaching, non-profits, youth work, community leadership"
};
const FIELD_PROMPTS = {
  make:   "When you make something, which part would you do for free: the idea, the building, or showing it to people?",
  move:   "When it got hard, did you want to stop, or did you want to find out how far you could go?",
  learn:  "What's the one question you couldn't stop thinking about afterwards, and have you looked it up yet?",
  social: "Did you come away energised by the people, or by what you learned from them?",
  nature: "What did you think about when everything went quiet, and why do you think that came up?",
  give:   "Would you still do it if nobody ever knew, and what does your answer say about what you value?"
};
