// THE QUESTS — the heart of Void. You can edit these without knowing how to code.
// Each quest is a real-world test: do it, then log how it felt. The pattern is what reveals your direction.
//
//   cat:  make | move | learn | social | nature | give
//   tier: recon (about 30 min, easy)  |  mission (1-2 hours)  |  trial (bigger, or uncomfortable)
//   why:  what this quest is designed to reveal about you
const QUESTS = [
  // ---- CREATE ----
  { id: 1,  cat: "make", tier: "recon",   time: "30 min",  title: "Make something ugly on purpose",
    desc: "Set a 30-minute timer. Draw, write, code, build or record anything. It has to be finished, not good.",
    why: "Separates enjoying the act of making from wanting to be good at it." },
  { id: 2,  cat: "make", tier: "recon",   time: "30 min",  title: "Write your own manual",
    desc: "Write 500 words on something you know better than most people: a game, a sport, a job, a way of fixing things. Write it like you're teaching a beginner.",
    why: "What you can explain without effort shows what you already care about." },
  { id: 3,  cat: "make", tier: "recon",   time: "30 min",  title: "Copy a master",
    desc: "Pick a piece of work you admire: a drawing, a song, a design, a paragraph. Spend 30 minutes recreating it as closely as you can.",
    why: "Copying shows the gap between what you see and what you can do, and whether closing that gap excites you." },
  { id: 4,  cat: "make", tier: "mission", time: "90 min",  title: "Follow a beginner tutorial start to finish",
    desc: "Pick a craft you've never tried: woodwork, music production, web design, cooking, photography, leatherwork. Find one beginner tutorial and finish it.",
    why: "A finished tutorial tells you if the craft itself pulls you, not just the idea of it." },
  { id: 5,  cat: "make", tier: "mission", time: "1-2 hours", title: "Fix something that's broken",
    desc: "A bike, a zip, a loose shelf, a laptop key, a bug in a free tool. Work out how, and fix it yourself.",
    why: "Some people come alive solving concrete problems. Find out if you do." },
  { id: 6,  cat: "make", tier: "mission", time: "1-2 hours", title: "Make something for one specific person",
    desc: "Build, cook, write or design something for a real person and hand it to them. No explaining it away.",
    why: "Shows whether you care more about the craft or about what it does for someone." },
  { id: 7,  cat: "make", tier: "trial",   time: "3-4 hours", title: "Ship a tiny project",
    desc: "Finish a small project in one sitting: a one-page site, a short film, a three-track demo, a piece of furniture from scrap wood. Then show it to one person and ask for honest feedback.",
    why: "Starting is easy. Finishing and showing are where most people stop. Notice which part you avoided." },

  // ---- BODY ----
  { id: 8,  cat: "move", tier: "recon",   time: "20 min",  title: "Push yourself for 10 hard minutes",
    desc: "Sprints, hill repeats, burpees, heavy carries, whatever suits you. Ten minutes at an effort you'd rate 8 out of 10. Stop if anything hurts wrong.",
    why: "How you handle discomfort shows what you're willing to work through." },
  { id: 9,  cat: "move", tier: "recon",   time: "30 min",  title: "Be a beginner at something physical",
    desc: "Follow a beginner video for something you've never tried: boxing, climbing technique, kettlebells, yoga, skateboarding basics.",
    why: "Being bad at something new reveals whether you enjoy the learning curve." },
  { id: 10, cat: "move", tier: "mission", time: "90 min",  title: "Ninety minutes of deliberate practice",
    desc: "Choose a skill: shooting hoops, swimming laps, bag work, bouldering, skating. Work on one weakness for 90 minutes and track what improved.",
    why: "Skill practice shows whether mastery pulls you harder than fitness alone." },
  { id: 11, cat: "move", tier: "mission", time: "45 min",  title: "Design and run your own training session",
    desc: "Write a 45-minute session with a clear goal, then run it. Adjust as you go and note what you'd change.",
    why: "Designing your own plan shows whether you like building systems or just following them." },
  { id: 12, cat: "move", tier: "mission", time: "1 hour",  title: "Train with someone better than you",
    desc: "Ask a friend or a gym regular who's better than you to train with you for an hour. Ask them one thing they wish they'd known at your level.",
    why: "Learning next to someone ahead of you shows whether their standard motivates you or intimidates you." },
  { id: 13, cat: "move", tier: "trial",   time: "Half a day", title: "Commit to a physical thing with a date",
    desc: "Register for a local run, a rec-league game, a trial class at a gym, or a martial arts intro session. Then go.",
    why: "Real commitments expose what you follow through on and what you talk yourself out of." },

  // ---- MIND ----
  { id: 14, cat: "learn", tier: "recon",   time: "30 min",  title: "List five times you lost track of time",
    desc: "Write down the last five moments you were so absorbed you forgot what time it was. Not what was productive. What actually absorbed you.",
    why: "Your past flow moments are the best clues you have. Look for the pattern." },
  { id: 15, cat: "learn", tier: "recon",   time: "20 min",  title: "Write the no-limits letter",
    desc: "Twenty minutes, no editing. Write a letter to yourself about what you would do with your life if money, opinions and fear of failing didn't exist.",
    why: "Removing the constraints shows what you actually want, not what you think you should want." },
  { id: 16, cat: "learn", tier: "mission", time: "90 min",  title: "Watch a real intro lecture in a field you know nothing about",
    desc: "Pick one: economics, psychology, medicine, architecture, law, astronomy, philosophy. Find a full university intro lecture and watch it with notes.",
    why: "Curiosity is the earliest sign of a path. Notice what you wanted to look up afterwards." },
  { id: 17, cat: "learn", tier: "mission", time: "1 hour",  title: "Study a career, not a success story",
    desc: "Pick someone whose work you respect. Read a long interview. Write down what they actually did each day when they started out.",
    why: "The daily reality matters more than the title. Would you want that Tuesday?" },
  { id: 18, cat: "learn", tier: "mission", time: "2 hours", title: "Do two hours of a beginner course",
    desc: "Khan Academy, freeCodeCamp, a language course, finance basics, design fundamentals. Two hours, with real notes.",
    why: "Two hours is long enough to know whether a subject pulls you or just sounds impressive." },
  { id: 19, cat: "learn", tier: "trial",   time: "1-2 hours", title: "Answer a hard question in writing",
    desc: "Pick one: What would I regret not trying? What do I keep avoiding? What do I do that other people find hard? Write 1,000 words.",
    why: "Long writing pushes past the easy answers to the real ones." },

  // ---- PEOPLE ----
  { id: 20, cat: "social", tier: "recon",   time: "15 min",  title: "Message someone whose work you admire",
    desc: "Send a short, specific note to someone doing work you respect. Say what you liked and ask one question. Don't ask for anything.",
    why: "Who you feel drawn to reach out to shows what you admire and might want to become." },
  { id: 21, cat: "social", tier: "recon",   time: "20 min",  title: "Ask three people what you're naturally good at",
    desc: "Text three people who know you well: \"What do you think I'm naturally good at?\" Ask for specific examples.",
    why: "Other people often see patterns in you that you can't." },
  { id: 22, cat: "social", tier: "mission", time: "45 min",  title: "Ask someone what their job is actually like",
    desc: "Find someone in a job you're curious about and ask: what does a normal Tuesday look like? What's the worst part? What surprised you?",
    why: "The daily reality of a job is what you'd be signing up for, not the title." },
  { id: 23, cat: "social", tier: "mission", time: "1 hour",  title: "Talk properly with someone twenty years older",
    desc: "A relative, a neighbour, a boss, a coach. Ask what they'd do differently at your age, and what they're glad they did.",
    why: "Looking back from further down the road makes your own options clearer." },
  { id: 24, cat: "social", tier: "trial",   time: "Half a day", title: "Ask a professional for a 20-minute call",
    desc: "Find someone in a field you're curious about: a friend of a friend, a local business owner, someone on LinkedIn. Ask for 20 minutes and prepare three questions.",
    why: "Asking for help is a skill and a signal. If you'd rather avoid this one, note that too." },
  { id: 25, cat: "social", tier: "trial",   time: "2-3 hours", title: "Go to something alone",
    desc: "A meetup, a talk, a workshop, a local league. Somewhere you know nobody. Stay at least an hour and talk to two people.",
    why: "Shows what kind of room you want to be in, and how you handle being the new one." },

  // ---- EXPLORE ----
  { id: 26, cat: "nature", tier: "recon",   time: "30 min",  title: "Go outside with no phone for 30 minutes",
    desc: "Leave it at home. Walk with no destination. Notice what you think about when nothing is competing for your attention.",
    why: "Silence brings up the things you've been avoiding thinking about." },
  { id: 27, cat: "nature", tier: "recon",   time: "30 min",  title: "Identify five things around you",
    desc: "Trees, birds, constellations, car engines, whatever is nearby. Look up the names of five things you've never bothered to learn.",
    why: "What you want to name shows what holds your attention." },
  { id: 28, cat: "nature", tier: "mission", time: "2 hours", title: "Take a long solo walk with no headphones",
    desc: "Two hours minimum, somewhere you've never been if you can. Bring water and tell someone where you're going.",
    why: "Long stretches alone with your thoughts surface the questions you're avoiding." },
  { id: 29, cat: "nature", tier: "mission", time: "1-2 hours", title: "Visit a place where people work",
    desc: "A workshop open day, a farm, a studio, a market, a fire station or factory tour. Watch people doing their jobs.",
    why: "You can only imagine a path if you've seen people on it." },
  { id: 30, cat: "nature", tier: "mission", time: "1-2 hours", title: "Navigate a route with only a map",
    desc: "Plan a route on a paper or offline map, then follow it on a walk without turn-by-turn GPS.",
    why: "Shows whether you enjoy figuring things out for yourself." },
  { id: 31, cat: "nature", tier: "trial",   time: "A full day", title: "Spend a whole day somewhere new",
    desc: "Take a train, bus or drive somewhere you've never been and be back by night. No plan except to look around and talk to one person.",
    why: "Unfamiliar places stretch your idea of what a life could look like." },

  // ---- SERVE ----
  { id: 32, cat: "give", tier: "recon",   time: "20 min",  title: "Do something useful for someone, unasked and unseen",
    desc: "Fix, carry, clean, pay for or organise something for someone. Don't tell them it was you.",
    why: "Notice whether doing good is enough without the credit." },
  { id: 33, cat: "give", tier: "recon",   time: "30 min",  title: "Thank someone who shaped you",
    desc: "A teacher, coach, relative or friend. Be specific about what they did and what it changed for you. Send it.",
    why: "Who you thank shows what you value." },
  { id: 34, cat: "give", tier: "mission", time: "45 min",  title: "Teach someone a skill you have",
    desc: "Anything real: a lift, a recipe, a game, a shortcut, a trade skill. Teach for at least 45 minutes.",
    why: "Teaching shows whether you get energy from passing things on." },
  { id: 35, cat: "give", tier: "mission", time: "1 hour",  title: "Help someone with a real problem",
    desc: "Ask someone close to you what they're stuck on. Spend an hour helping them make progress on it.",
    why: "Solving other people's problems shows what kind of problems you're drawn to." },
  { id: 36, cat: "give", tier: "mission", time: "One shift", title: "Volunteer for one shift",
    desc: "Food bank, animal shelter, community clean-up, youth sports. Sign up and show up for a full shift.",
    why: "Some people find their direction in serving. See whether you feel it." },
  { id: 37, cat: "give", tier: "trial",   time: "1-2 hours", title: "Mentor or coach someone for an hour",
    desc: "Offer to help someone younger with homework, a sport, a job application or a skill. Show up prepared.",
    why: "Responsibility for another person's progress shows what kind of leader you'd be." },

  // ================= PREMIUM PACK: THE BUILDER PATH =================
  { id: 101, pack: "builder", cat: "learn", tier: "recon", time: "30 min", title: "Find a problem worth solving",
    desc: "List ten things that annoyed you this week, big or small. Circle the three other people probably share.",
    why: "Every real business starts with a problem you're close enough to feel." },
  { id: 102, pack: "builder", cat: "learn", tier: "recon", time: "30 min", title: "Study a business near you",
    desc: "Pick a local business. Work out who pays them, for what, and how they probably got their first customers.",
    why: "Seeing how money actually moves makes building something feel less abstract." },
  { id: 103, pack: "builder", cat: "social", tier: "mission", time: "1 hour", title: "Ask three people about a problem",
    desc: "Pick a problem you care about. Ask three people whether they have it and what they do about it now. Don't pitch anything. Just listen.",
    why: "Listening before building is the skill most first-time founders skip." },
  { id: 104, pack: "builder", cat: "make", tier: "mission", time: "2 hours", title: "Build the smallest possible test",
    desc: "A one-page site, a mock-up, a spreadsheet, a short pitch. Anything a stranger could react to in under a minute.",
    why: "Shows whether you enjoy turning an idea into something real, fast and rough." },
  { id: 105, pack: "builder", cat: "make", tier: "mission", time: "1 hour", title: "Put a price on it",
    desc: "Decide what your idea would cost and write down why. Then ask two people whether it feels fair.",
    why: "Pricing forces you to believe your idea is worth something." },
  { id: 106, pack: "builder", cat: "learn", tier: "mission", time: "90 min", title: "Read a founder's first year",
    desc: "Find a long, honest account of a founder's first year: an interview, a podcast, a blog. Note the unglamorous parts.",
    why: "If the boring parts sound bearable, that's a strong sign." },
  { id: 107, pack: "builder", cat: "social", tier: "trial", time: "3 hours", title: "Get a stranger to say yes or no",
    desc: "Show what you made to someone you don't know and ask them to buy it, sign up or commit. A no counts as a win.",
    why: "Handling rejection decides whether you can build anything for other people." },
  { id: 108, pack: "builder", cat: "give", tier: "trial", time: "3 hours", title: "Solve it for one person for free",
    desc: "Offer to solve the problem for one person at no charge. Do it properly. Notice how it feels to be useful.",
    why: "Shows whether the work itself, not the money, is what pulls you." },

  // ================= PREMIUM PACK: HANDS & TRADES =================
  { id: 111, pack: "trades", cat: "social", tier: "recon", time: "20 min", title: "Ask a tradesperson what they'd tell a 20-year-old",
    desc: "An electrician, carpenter, mechanic, plumber, welder. Ask what the job is really like and how they got started.",
    why: "Trades are well paid and under-explored. Hear it from someone actually doing it." },
  { id: 112, pack: "trades", cat: "learn", tier: "recon", time: "30 min", title: "Look up three apprenticeships",
    desc: "Find the entry route, length, pay and requirements for three trades near you. Write them side by side.",
    why: "A real path is easier to want when you can see its first step." },
  { id: 113, pack: "trades", cat: "make", tier: "mission", time: "90 min", title: "Do a small repair with real tools",
    desc: "Replace a tap washer, patch a wall, change a bike chain, swap a plug. Follow a tutorial and do it for real.",
    why: "Hands-on work either feels satisfying or it doesn't. Find out which." },
  { id: 114, pack: "trades", cat: "nature", tier: "mission", time: "1-2 hours", title: "Watch a trade at work",
    desc: "Ask a local tradesperson or workshop if you can watch for an hour. Notice the pace, the tools and the mood.",
    why: "You can only picture yourself in a job after you've seen it up close." },
  { id: 115, pack: "trades", cat: "move", tier: "mission", time: "3 hours", title: "Do a physical day's labour",
    desc: "Help someone move house, dig a garden, build a fence or clear a space. Three hours of real physical work.",
    why: "Shows whether you enjoy work that ends in something you can see." },
  { id: 116, pack: "trades", cat: "learn", tier: "mission", time: "90 min", title: "Learn to read a plan or diagram",
    desc: "Learn to read a basic floor plan, wiring diagram or technical drawing. Find a beginner guide and work through one example.",
    why: "Technical thinking is the core of most skilled trades." },
  { id: 117, pack: "trades", cat: "make", tier: "trial", time: "4 hours", title: "Build something that has to hold weight",
    desc: "A shelf, a bench, a frame. It has to work, and it has to survive being used.",
    why: "When it has to work, you find out how you handle precision and mistakes." },
  { id: 118, pack: "trades", cat: "social", tier: "trial", time: "Half a day", title: "Ask for a day of work experience",
    desc: "Contact a local business and ask if you can shadow someone for a day. Be polite, clear and ready to be told no.",
    why: "Asking for the chance is itself a test of how much you want it." },

  // ================= PREMIUM PACK: CREATIVE PATHS =================
  { id: 121, pack: "creative", cat: "make", tier: "recon", time: "30 min", title: "Make ten rough versions",
    desc: "Take one idea (a logo, a hook, a scene, a sketch) and make ten rough versions in 30 minutes. Don't judge until all ten exist.",
    why: "Creative careers reward volume. See whether you enjoy the churn." },
  { id: 122, pack: "creative", cat: "learn", tier: "recon", time: "30 min", title: "Break down something you love",
    desc: "Take a film scene, a song or a design you love and work out exactly why it works.",
    why: "What you notice shows what you're drawn to making." },
  { id: 123, pack: "creative", cat: "make", tier: "mission", time: "2 hours", title: "Finish a piece under constraints",
    desc: "Set tight rules: one colour, three chords, 100 words, one location. Finish something in two hours.",
    why: "Constraints show whether you get energy from limits or feel stifled by them." },
  { id: 124, pack: "creative", cat: "social", tier: "mission", time: "45 min", title: "Ask a working creative how they get paid",
    desc: "Message or meet someone who earns from creative work. Ask how they started, how they price their work and what the first year was like.",
    why: "The money side of creative work is where most dreams get tested." },
  { id: 125, pack: "creative", cat: "make", tier: "mission", time: "15 min a day, 7 days", title: "Run a seven-day practice",
    desc: "Pick one creative practice and do 15 minutes a day for seven days. Log it, even when it's bad.",
    why: "Seven days is enough to show whether you want to keep going once it's no longer new." },
  { id: 126, pack: "creative", cat: "learn", tier: "mission", time: "90 min", title: "Study how a creative career really works",
    desc: "Pick a career: illustration, audio engineering, game design, filmmaking. Find out how people earn, what the entry jobs are and what a typical week looks like.",
    why: "Knowing the real shape of a career lets you decide whether you want it." },
  { id: 127, pack: "creative", cat: "social", tier: "trial", time: "2 hours", title: "Show unfinished work to a stranger",
    desc: "Share something half-done with someone you don't know and ask what they notice. Don't defend it.",
    why: "Tolerance for feedback is one of the biggest predictors of a creative career." },
  { id: 128, pack: "creative", cat: "make", tier: "trial", time: "4 hours", title: "Make something for a real deadline",
    desc: "Pick a real deadline: a friend's birthday, a local event, a submission date. Make something for it and ship it on time.",
    why: "Deadlines show whether you work better under pressure or in spite of it." }
];

// Premium quest packs (sold in the Shop). Quests with a "pack" only appear once that pack is owned.
const PACKS = {
  builder:  { name: "The Builder Path", tag: "For people who want to start something of their own." },
  trades:   { name: "Hands & Trades",   tag: "Test skilled trades and practical, physical work." },
  creative: { name: "Creative Paths",   tag: "Find out if a creative career is really for you." }
};

// Used by the Direction Report. Not career advice: just paths people with each signal often explore.
const FIELD_PATHS = {
  make:   "design, engineering, film and video, game development, architecture, the skilled trades",
  move:   "coaching, physiotherapy, sports science, emergency services, the military, outdoor education",
  learn:  "research, engineering, medicine, law, data and analysis, writing",
  social: "sales, teaching, counselling, recruiting, management, community work",
  nature: "surveying, logistics, conservation, travel and hospitality, field work, outdoor roles",
  give:   "nursing, social work, teaching, non-profits, youth work, community leadership"
};
const FIELD_PROMPTS = {
  make:   "When you make something, which part would you do for free: the idea, the building, or showing it to people?",
  move:   "When it got hard, did you want to stop, or did you want to find out how far you could go?",
  learn:  "What's the one question you couldn't stop thinking about afterwards, and have you looked it up yet?",
  social: "Did you come away energised by the people, or by what you learned from them?",
  nature: "What did you think about when everything went quiet, and why do you think that came up?",
  give:   "Would you still do it if nobody ever knew, and what does your answer say about what you value?"
};

const TIERS = {
  recon:   { label: "Recon",   xp: 50,  gear: "common" },
  mission: { label: "Mission", xp: 100, gear: "rare" },
  trial:   { label: "Trial",   xp: 200, gear: "epic" }
};

// The six fields you sweep in Phase 1. "ask" is the reflection prompt shown after a quest in that field.
const CATEGORIES = {
  make:   { label: "Create",  color: "#c58a9f", ask: "Which part did you like most: starting, making, or finishing?" },
  move:   { label: "Body",    color: "#c9965c", ask: "How did you feel when it got hard?" },
  learn:  { label: "Mind",    color: "#6f97b8", ask: "What did you want to look up next?" },
  social: { label: "People",  color: "#c47f6c", ask: "What did you learn about what they actually do or feel?" },
  nature: { label: "Explore", color: "#6f9f86", ask: "What did you think about when it went quiet?" },
  give:   { label: "Serve",   color: "#c4ad72", ask: "What did it feel like to do it?" }
};
